#!/usr/bin/env bash
# A script that sets up and configures HAproxy on your lb-01 server

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install haproxy

echo "

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 293215-web-01 107.23.62.11:80 check
    server 293215-web-02 54.146.84.51:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
